---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(lubridate)
```

```{r}
job = read.csv("jobs.csv")
companies=read.csv("companies.csv")
demographics = read.csv("demographics.csv")
econ_federal=read.csv("econ_federal.csv")
econ_state=read.csv("econ_state.csv")
education=read.csv("education.csv")
geographic=read.csv("geographic.csv")
industries = read.csv("industries.csv")
real_estate=read.csv("real_estate.csv")
```

```{r}
df = inner_join(job, companies)
df = inner_join(df, econ_state)
df = inner_join(df, real_estate)
df = inner_join(df, demographics)


```

```{r}
df1 = df%>%
  mutate(state = as.numeric(state))%>%
  group_by(state)%>%
  summarise(n())

```
```{R}
#preprocess for job
job$year <- year(ymd(job$created_date))
job$month <- month(ymd(job$created_date))
job$date <- day(ymd(job$created_date))

job = job%>%
  mutate(quarter = floor((month -1)/3)+ 1,
         time = paste0(year, "-", quarter))%>%
  select(-year,-month,-quarter)

job = write.csv(job,"job.csv")
```

```{r}
substr(names(econ_state[,3]), 1,4)

```

```{r}
#preprocess for econ
econ = read.csv("econ_state_new.csv")

econ = econ%>%
  mutate(Q=quarter)%>%
  select(-quarter)

for( i in 1: nrow(econ)){
       econ$year[i] = substr(econ[i,6], 1, 4)
       econ$quarter[i] = substr(econ[i,6], 6,6)
        
}

econ = econ%>%
  mutate(time = paste0(year, "-", quarter))%>%
  select(-year,-quarter,-Q)

econ = write.csv(econ, "econ_state.csv")

```



